/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#133e48",
        "surface-container-highest": "#e4e2de",
        "outline-variant": "#c1c8ca",
        "secondary-fixed": "#ffdad2",
        "inverse-primary": "#a4cdd9",
        "surface": "#fbf9f5",
        "primary-fixed-dim": "#a4cdd9",
        "on-tertiary-fixed-variant": "#00513d",
        "on-error": "#ffffff",
        "on-surface": "#1b1c1a",
        "tertiary-fixed": "#92f5d0",
        "outline": "#71787b",
        "surface-variant": "#e4e2de",
        "on-primary-fixed-variant": "#244c56",
        "tertiary-container": "#004130",
        "secondary-fixed-dim": "#ffb4a3",
        "on-tertiary-fixed": "#002117",
        "primary-fixed": "#c0e9f6",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#4fb391",
        "tertiary": "#00291d",
        "surface-container": "#efeeea",
        "background": "#fbf9f5",
        "on-surface-variant": "#41484a",
        "secondary-container": "#fd6442",
        "surface-dim": "#dbdad6",
        "on-tertiary": "#ffffff",
        "secondary": "#b02e10",
        "surface-bright": "#fbf9f5",
        "error": "#ba1a1a",
        "primary": "#002830",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3ef",
        "on-primary-fixed": "#001f26",
        "tertiary-fixed-dim": "#76d9b5",
        "on-background": "#1b1c1a",
        "surface-tint": "#3d646f",
        "on-primary-container": "#81a9b5",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#3d0600",
        "on-secondary-container": "#600e00",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#8c1900",
        "inverse-on-surface": "#f2f0ed",
        "surface-container-high": "#eae8e4",
        "inverse-surface": "#30312e"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-md": "1rem",
        "space-xl": "2rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        gutter: "1rem",
        "space-sm": "0.5rem",
        margin: "1.25rem"
      },
      fontFamily: {
        "label-badge": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "display-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        display: ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "label-badge": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "19px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "700" }],
        "body-md": ["15px", { lineHeight: "23px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["17px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "400" }],
        display: ["36px", { lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "800" }]
      }
    }
  }
};
